import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "@/css/euclid-circular-a-font.css";
import "@/css/style.css";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { NextAuthProvider } from "@/components/providers/authProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // supress client and server warning
    <html lang="en" suppressHydrationWarning={false}>
      <body>
        <>
          <NextAuthProvider>
            <Header />
            {children}
            <Footer />
          </NextAuthProvider>
        </>
      </body>
    </html>
  );
}
